[project]
name = "planager"
description = "Package for planning and time tracking."
version = "0.1.0"
authors = [
    { name = "Isaac Riley", email = "isaac.r.riley@gmail.com" }
]
dependencies = []

[project.optional-dependencies]
dev = [
    "tox",
    "pre-commit",
]